org.gradle.jvmargs=-Xmx4G
enabled_platforms=fabric,neoforge
minecraft_version=1.21.8
parchment_version=1.21.8:2025.07.18
# NeoForge Properties
neo_loader_version=2
neoforge_version=21.8.13
# Fabric Properties
fabric_loader_version=0.16.14

# Mod Properties
mod_version=1.0.5
maven_group=io.github.flemmli97
archives_base_name=lingua_bib

# Dependencies
# currently not on the main fabric site, check on the maven: https://maven.fabricmc.net/net/fabricmc/fabric-api/fabric-api
fabric_version=0.129.0+1.21.8
fabric_permissions_api=0.4.0
ftb_ranks=2100.1.0

# Other
project_name=LinguaBibliotheca
