org.gradle.jvmargs=-Xmx4G
enabled_platforms=fabric,neoforge
minecraft_version=1.21.1
neoForm_version=1.21.1-20240808.144430
parchment_minecraft=1.21
parchment_version=2024.07.28
# NeoForge Properties
neo_loader_version=2
neoforge_version=21.1.4
# Fabric Properties
fabric_loader_version=0.15.11

# Mod Properties
mod_version=1.0.6
maven_group=io.github.flemmli97
mod_id=lingua_bib
mod_author=flemmli97

# Dependencies
# currently not on the main fabric site, check on the maven: https://maven.fabricmc.net/net/fabricmc/fabric-api/fabric-api
fabric_version=0.116.4+1.21.1
fabric_permissions_api=0.3.3
ftb_ranks=2100.1.0

# Other
project_name=LinguaBibliotheca
