modLoader="javafml"
loaderVersion="[${loader_version},)"
license="MIT"
issueTrackerURL="https://github.com/Flemmli97/LinguaBibliotheca/issues"
[[mixins]]
config="lingua_bib.mixins.json"
[[mods]]
modId="lingua_bib"
version="${version}"
displayName="Lingua Bibliotheca"
authors="Flemmli97"
description='''Server side translation API'''
[[dependencies.lingua_bib]]
modId="minecraft"
type="required"
versionRange="[${mcversion},)"
ordering="NONE"
side="BOTH"
[[dependencies.lingua_bib]]
modId="neoforge"
type="required"
versionRange="[${forge_version},)"
ordering="NONE"
side="BOTH"
